#!/bin/bash
#
sudo /home/pi/pi-camera/multi-gadget.sh
/usr/bin/v4l2-ctl -c auto_exposure=0
/usr/bin/v4l2-ctl -c auto_exposure_bias=12
/usr/bin/v4l2-ctl -c contrast=4
/usr/bin/v4l2-ctl -c video_bitrate=25000000
/usr/bin/v4l2-ctl -c brightness=55
sudo /home/pi/pi-camera/uvc-gadget -f1 -s2 -r1  -u /dev/video1 -v /dev/video0

